---
# Prometheus Node Exporter
node_exporter_version: "1.8.2"
node_exporter_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
node_exporter_port: 9100
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"

# OpenTelemetry Collector Contrib
enable_otelcol: true
otelcol_version: "0.108.0"
otelcol_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
otelcol_user: "otelcol-contrib"
otelcol_group: "otelcol-contrib"

# Docker Metrics Scrape Toggle
docker_metrics_enabled: false
docker_metrics_address: "127.0.0.1:9323"

# OpenTelemetry Target Backend Endpoint
otel_target_endpoint: "127.0.0.1:4317"
otel_target_insecure: true
otel_target_headers: {}
otel_auth_header: ""

# OpenTelemetry Collector System Logs to Ingest (ISMS/ISMS-P Baseline)
otel_system_logs:
  - /var/log/messages
  - /var/log/syslog
  - /var/log/secure
  - /var/log/auth.log
  - /var/log/sudo.log
  - /var/log/audit/audit.log
  - /var/log/cron*
  - /var/log/fail2ban.log
  - /var/log/dnf.log
  - /var/log/yum.log
  - /var/log/dpkg.log
  - /var/log/firewalld

