---
# storage-01 호스트 전용 개별 변수 오버라이드
firewall_allowed_tcp_ports:
  - 22    # SSH
  - 9100  # Node Exporter
  - 2049  # NFS
  - 3260  # iSCSI target

# 특정 호스트 전용 커널 파라미터 추가
sysctl_settings:
  fs.file-max: 4194304
  vm.dirty_ratio: 20
  vm.dirty_background_ratio: 10
