---
all:
  children:
    # 1. Overseer 컨트롤 플레인 전용 서버 그룹 (OpenBao, Boundary, Docker Engine)
    overseer:
      hosts:
        ns0333.nanoit.kr:
          ansible_host: 39.116.31.40
          ansible_user: ppzxc
          ansible_port: 22

    # 2. 온프레미스 IDC 일반 서버 그룹 (Target Nodes)
    servers:
      hosts:
        ns0266.nanoit.kr:
          ansible_host: 39.116.31.43
          ansible_user: root
          ansible_port: 8487
