---
all:
  children:
    # 1. IDC 전체 서버 그룹
    idc_servers:
      children:
        # 역할(Role) 기반 그룹
        compute_nodes:
          hosts:
            ns0333.nanoit.kr:
              ansible_host: 39.116.31.40
              ansible_user: ppzxc
              ansible_port: 22
        modern_rocky_nodes:
          hosts:
            ns0333.nanoit.kr:
