services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    image: overseer-ansible:latest
    volumes:
      - .:/ansible
      - ~/.ssh:/root/.ssh:ro
    environment:
      - ANSIBLE_FORCE_COLOR=True
      - VAULT_ADDR=${VAULT_ADDR:-}
      - VAULT_TOKEN=${VAULT_TOKEN:-}
    working_dir: /ansible
    entrypoint: ["ansible-playbook"]
    command: ["--help"]
